---
  AWSTemplateFormatVersion: '2010-09-09'
  Transform: AWS::Serverless-2016-10-31
  Description: API Proxy for Ex Libris Cloud Apps
  Parameters:
    AllowedApps:
      Type: String
      Description: Comma separated list of app names
      Default: ''
    AllowedInstCodes:
      Type: String
      Description: Comma separated list of institution codes
      Default: ''
    AllowLocalhost:
      Type: String
      Description: Allow calls from development environments; true/false
      Default: ''      
  Resources:
    Dependencies:
      Type: "AWS::Serverless::LayerVersion"
      Properties:
        LayerName: !Sub "${AWS::StackName}-Dependencies"
        ContentUri: ./dependencies
        CompatibleRuntimes:
          - nodejs10.x
          - nodejs12.x
        LicenseInfo: 'Apache-2.0'
    CloudAppProxy:
      Type: AWS::Serverless::Function
      Properties:
        FunctionName: !Sub "${AWS::StackName}-Function"
        CodeUri: ./src
        Layers:
          - !Ref Dependencies
        Handler: handler.handler
        Events:
          ProxyApi:
            Type: HttpApi
        Runtime: nodejs12.x
        Timeout: 60
        Environment:
          Variables:
            CLOUDAPP_AUTHORIZER_ALLOWED_APPS: !Ref AllowedApps
            CLOUDAPP_AUTHORIZER_ALLOWED_INST_CODES: !Ref AllowedInstCodes
            CLOUDAPP_AUTHORIZER_ALLOW_LOCALHOST: !Ref AllowLocalhost
  Outputs:
    ApiUrl:
      Description: URL of the API proxy
      Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/"

  